top:
	vcs -debug primitives.v TAP.v JTAG.v s9234_JTAG_TOP.v s9234_JTAG_BSR.v \
		s9234.v s9234_inscan.v TB_DUT2.v

ref:
	vcs -debug primitives.v s9234_test2.v ref_tb.v

ir:
	vcs -debug primitives.v TAP.v JTAG.v ir_tb.v
